name: Auto approve

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/actions/github/auto-approve@0.18.0
        if: >-
          contains(github.event.pull_request.labels.*.name, 'auto-approve') && github.event.pull_request.head.repo.full_name == github.repository
        with:
          test1: ${{ contains(github.event.pull_request.labels.*.name, 'auto-approve') }}
          test2: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
