name: Auto merge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/actions/github/auto-merge@0.18.0
        if: |
          contains(github.event.pull_request.labels.*.name, 'auto-merge')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: auto-merge,!wip
          UPDATE_LABELS: auto-merge
          MERGE_METHOD: "squash"
          UPDATE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_FORKS: "false"
          MERGE_DELETE_BRANCH: "true"
